### ISSUE TITLE
PHIP-Seq Pipeline Issue

### ISSUE THREAD

**Issue by aaronliuUBC** [lasersonlab/pepsyn#15]
Hi,

I am having issues with the PHIP-Seq pipeline from your Nature Protocol. When I run step 4 I get error out after running this:

`PREFIX=AGGAATTCCGCTGCGT
SUFFIX=GCCTGGAGACGCCATC
PREFIXLEN=${#PREFIX}
SUFFIXLEN=${#SUFFIX}
FREQTHRESH=0.01
cat protein_tiles.fasta \
| pepsyn revtrans --codon-freq-threshold $FREQTHRESH --amber-only
--\
| pepsyn prefix -p $PREFIX - - \
| pepsyn suffix -s $SUFFIX - - \
| pepsyn recodesite --site EcoRI –site HindIII --clip-left $PREFIXLEN \
--clip-right $SUFFIXLEN --codon-freq-threshold $FREQTHRESH \
--amber-only - - \
>oligos.fasta`

`Usage: pepsyn recodesite [OPTIONS] INPUT OUTPUT
Try "pepsyn recodesite -h" for help.

Error: Invalid value for "INPUT": Could not open file: –-site: No such file or directory`

I have run each line separately, but it seems to be really hungup on the step of "recodesite"...

**Comment by laserson** [comment]
Sorry about that @aaronliuUBC! I think you may have copy/pasted from the Nature Protocols. Someone just last week also reported a typo. In the Nature Protocols site, the flag is written as `–site` but it SHOULD be `--site` (note the double hyphen instead of just a single n-dash).

Please reopen if there are still problems. Thanks for reporting the issue!
