### ISSUE TITLE
Suffix containing stop codon and restriction site

### ISSUE THREAD

**Issue by MHendling** [lasersonlab/pepsyn#18]
Hello,

with this message I want to refer to a paper called "PhIP-Seq characterization of serum antibodies using oligonucleotide-encoded peptidomes" from 2018 by Divya Mohan et al. They were using pepsyn for the peptide design and gave a very detailed description of the worklfow they used. However, the authors used a suffix that did not start with the specified stop codon and did not include the restriction site used in the command "pepsyn recodesite --site....". Therefore, we were wondering if it is a mistake in the paper or if it is not necessary to have a suffix starting with the specified stop codon and including the specified restriction site?

Thanks in advance!

**Comment by laserson** [comment]
There may have been a typo in the paper, but it would be easier if you could share what error you're getting.

**Comment by MHendling** [comment]
Thank you for the quick response. Actually, we are not getting any error on the software side. The software was running without any error till the end. My question refers more to the subsequent lab steps. It's the first time for us designing such peptides, therefore we want to make sure that everything is correct. 
We were just wondering if the suffix needs to include the stop codon at the beginning and the used restriction site within the sequence (because that's what we think is correct). The suffix used in the above mentioned paper is "GCCTGGAGACGCCATC" and they used it with the HindIII restriction site and the amber stop codon. However, the suffix doesn't start with the amber stop codon and also doesn't contain the HindIII restriction site. But we thought it would be necessary that the suffix contains both. 

Thanks for your help.

**Comment by laserson** [comment]
Hmm, I think the stop codon was added to the "peptide sequence" part of the oligo and only for the C-terminal peptides. The suffix sequence is a constant sequence added to the oligos mainly used for PCR and cloning. What you put in it entirely depends on the structure of your gene cassette and cloning strategy. Just make sure you take an example peptide and pass it through your flow to make sure you've designed it correctly.

**Comment by RChGO** [comment]
Hello, the following command is from the [Mohan Nature Protocols paper](https://www.nature.com/articles/s41596-018-0025-6). I'm a bit confused myself: does "SUFFIX" need to include the restriction site? If "SUFFIX" doesn't need to include the restriction site, then is "--site HindIII" not necessary at the "pepsyn recodesite" step?
```
PREFIX=AGGAATTCCGCTGCGT  # The sequence contain the EcoRI restriction site. 
SUFFIX=GCCTGGAGACGCCATC # The sequence does not contain the HindIII restriction site.
PREFIXLEN=${#PREFIX} 
SUFFIXLEN=${#SUFFIX} 
FREQTHRESH=0.01 
cat protein_tiles.fasta \
    | pepsyn revtrans  --codon-freq-threshold $FREQTHRESH --amber-only - - \
    | pepsyn prefix -p $PREFIX - - \
    | pepsyn suffix -s $SUFFIX - - \
    | pepsyn recodesite --site EcoRI  --site HindIII --clip-left $PREFIXLEN \
    --clip-right $SUFFIXLEN --codon-freq-threshold $FREQTHRESH \
    --amber-only - - >oligos.fasta
```

**Comment by laserson** [comment]
`recodesite` ensures that each oligo sequence that is passed into it will not have any EcoR1 or HindIII sites (as invoked in your example). In order to ensure that, it will select different codons while keeping the underlying amino acid sequence constant. In order to recode the oligo sequence, it needs to know which part of the sequence is actually coding. If you're not using HindIII in your cloning strategy, then you probably don't need to worry about HindIII sites.

The `prefix` and `suffix` command literally just add a prefix or suffix sequence to each sequence that is input into the command. (It's just a convenience utility.) Usually when you order oligo pools there is a common 5' and 3' sequence which is used for PCR. Based on your cloning strategy, the "prefix" or "suffix" may or may not contain restriction sites...that's entirely up to you.
