### ISSUE TITLE
Prefix suffix attached then removed?

### ISSUE THREAD

**Issue by mattohewitt** [lasersonlab/pepsyn#19]
Hi, from the [Mohan Nature Protocols paper](https://www.nature.com/articles/s41596-018-0025-6), would anybody be able to tell me why adapters are seemingly added then in the same command removed?

```
PREFIX=AGGAATTCCGCTGCGT # T7-VirScan_SP
SUFFIX=GCCTGGAGACGCCATC # Are these actual suggested pcr primer / binding sequences?
PREFIXLEN=${#PREFIX} 
SUFFIXLEN=${#SUFFIX} 
FREQTHRESH=0.01 
cat results/intermediates/"$organism"_protein_tiles.fasta \
    | pepsyn revtrans \
    --codon-freq-threshold $FREQTHRESH \
    --amber-only - - \
    | pepsyn prefix -p $PREFIX - - \
    | pepsyn suffix -s $SUFFIX - - \
    | pepsyn recodesite \
    --site EcoRI \
    --site XhoI \
    --clip-left $PREFIXLEN \
    --clip-right $SUFFIXLEN \
    --codon-freq-threshold $FREQTHRESH \
    --amber-only - - > results/outputs/"$organism"_oligos.fasta
```
    
Thanks, 
Matt

**Comment by laserson** [comment]
Are you referring to `--clip-left` and `--clip-right` when you say they are seemingly removed?

They are not removed again. The `recodesite` command will try to find an alternate coding for the same amino acid sequence. Because you've added adaptors, you need to tell the command where to start and stop recoding (because you don't want to touch the adaptors). That's what the `--clip-left` and `--clip-right` options specify. The reason you have to recode at this stage is because concatenating the adaptors could introduce new forbidden sites that didn't exist without the adaptor.

**Comment by mattohewitt** [comment]
Amazing, thanks for the clarification!

Thanks, 
Matt
