### ISSUE TITLE
revtrans obfuscating tile overlap?

### ISSUE THREAD

**Issue by dpschreiner** [lasersonlab/pepsyn#21]
hi, i am running the code as outlined in the 2018 paper and when i execute revtrans, i can no longer observe the overlap in my sequences that i created with the amino acid sequences.  is this normal?  is it a function of the random codon sampling of the revtrans?  when is a custom codon table advised?  is this random selection of codons different for each new aa sequence?

--codon-freq-threshold 0.01

when i use pepsyn translate to go back to aa, the result is identical to peptide_tiles.fasta which was the (correctly overlapping) input to the revtrans command.

the trigger for all of this was: the resulting oligos were synthesized (before i noticed this!) and alignment of the PCR amplified library to the same reference is < 2%.

thanks in advance!

**Comment by laserson** [comment]
It's hard to say for sure without more context, but you are likely correct that this is due to `revtrans` sampling codons randomly. Since there isn't a unique mapping from amino acid seq => nucleotide sequence, overlapping amino acid subsequences may get non-overlapping nucleotide subsequences. Hopefully this doesn't break your experiment!
